config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root 'static_pages#home'
  get "home" => 'static_pages#home'
  get "help" => 'static_pages#help'
  get "about" => 'static_pages#about'
  get "contact" => 'static_pages#contact'
  get "newuser" => 'users#new'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
    validates :name , presence: true, length: {maximum: 50}, uniqueness: true
    validates :email , presence: true  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  def say_hello
    puts "modify check"  
    render html: "Hello World!"
  end
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def home
  end
  
  def help
  end

  def about
  end
  
  def contact
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    
    def get_base_title(pageTitle = "")
        pageTit = "Ruby Rails Page"
        if pageTitle != ""
           pageTit = "Ruby Rails #{pageTitle} Page" 
        end    
        pageTit
    end    
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
    
    def get_page_name(pageName = "")
        pageNam = pageName
        if pageName == ""
           pageNam = "home" 
        end    
        pageNam
    end 
    
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">

  <small>

    The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>

    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>

  </small>

  <nav>

    <ul>
          <li><%= link_to "About", about_path %></li>

      <li><%= link_to "Contact", contact_path %></li>

      <li><a href="http://news.railstutorial.org/">News</a></li>

    </ul>

  </nav>

</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "Sample APP", root_path , {id: "logo"} %>
      </div>
      <nav>
        <ul class="nav navbar-nav pull-right">
          <li><%= link_to "home",root_path , {id: "home"} %></li>
          <li><%= link_to "help",help_path , {id: "help"} %></li>
          <li><%= link_to "login","#" , {id: "login"} %></li>
        </ul> 
      </nav>
    </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>
      <%= get_base_title(yield :title)%>
      
    </title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <%= yield %>
    </div>
    <li><%= link_to image_tag("Ruby_on_Rails-logo.png", alt: "rails logo" , size: "20x20"), "https://www.tutorialspoint.com/ruby-on-rails/" %></li>
    
      <%= render 'layouts/footer' %>
      
  </body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title , "about") %>

  <h1>About page</h1>
  <p>This is the about page of <a href="https://www.youtube.com/"><%= get_page_name yield(:title)%> page !</a></p>

app/views/static_pages/contact.html.erb
<% provide(:title , "contact") %>

  <h1>Contact Info</h1>
  <p>This is the Contact page of 
  <a href="https://www.tutorialspoint.com/ruby-on-rails/"><%= get_page_name yield(:title)%> page !</a></p>

app/views/static_pages/help.html.erb
<% provide(:title , "help") %>
<h1>Help page</h1>
<p>This is the help page of <a href="https://www.yahoo.com/"><%= get_page_name yield(:title)%> page !</a></p>

app/views/static_pages/home.html.erb
    <div class= "jumbotron center">
    <body>
        <h1>Welcome to sample APP</h1>
        <h2>This is the home page for
            <a href="https://www.tutorialspoint.com/ruby-on-rails/">ruby on rails tutorial</a>
            sample application
        </h2>
        <li><%= link_to "Sign Up now", newuser_path , {class: "btn btn-lg btn-primary"} %></li>
    </body>
    </div>

app/views/users/new.html.erb
<% provide :title , "Sign up"%>
<h1>Register</h1>
<p>please enter your details to register</p>